extends: "./_universal_common.yaml"

retargeting:
  vector_constraints:
    - human: [1, 2]
      robot: ["thumb_proximal_base", "thumb_proximal"]
    - human: [2, 3]
      robot: ["thumb_proximal", "thumb_intermediate"]
    - human: [3, 4]
      robot: ["thumb_intermediate", "thumb_distal_tip"]
      robot_types: ["body", "site"]
    - human: [5, 7]
      robot: ["index_proximal", "index_intermediate"]
    - human: [7, 8]
      robot: ["index_intermediate", "index_intermediate_tip"]
      robot_types: ["body", "site"]
    - human: [9, 11]
      robot: ["middle_proximal", "middle_intermediate"]
    - human: [11, 12]
      robot: ["middle_intermediate", "middle_intermediate_tip"]
      robot_types: ["body", "site"]
    - human: [13, 15]
      robot: ["ring_proximal", "ring_intermediate"]
    - human: [15, 16]
      robot: ["ring_intermediate", "ring_intermediate_tip"]
      robot_types: ["body", "site"]
    - human: [17, 19]
      robot: ["pinky_proximal", "pinky_intermediate"]
    - human: [19, 20]
      robot: ["pinky_intermediate", "pinky_intermediate_tip"]
      robot_types: ["body", "site"]
  distance_constraints:
    - human: [4, 8]
      robot: ["thumb_tip", "index_tip"]
      robot_types: ["site", "site"]
    - human: [4, 12]
      robot: ["thumb_tip", "middle_tip"]
      robot_types: ["site", "site"]
    - human: [4, 16]
      robot: ["thumb_tip", "ring_tip"]
      robot_types: ["site", "site"]
    - human: [4, 20]
      robot: ["thumb_tip", "pinky_tip"]
      robot_types: ["site", "site"]
  frame_constraints:
    - name: "thumb_cmc_frame"
      human_origin: 1
      human_primary: 2
      human_secondary: 5
      robot_origin: "thumb_proximal_base"
      robot_primary: "thumb_proximal"
      robot_secondary: "index_proximal"
